mri2mesh/fs2zef: initial improvements
sampsapursiainen/zeffiro_interface pull request #193
Opened 2023-04-22 09:57 UTC by SeSodesa

- Allow `.dat` files in the subdirectories of this project via `.gitignore`.

- Use the `-batch` instead of `-r` switch when calling Matlab, so Matlab does not expect any input from the user (requires Matlab R2019a).

- Remove the unnecessarily long Matlab scripts and move them to two Matlab functions: `save_color_tables.m` and `save_dats.m`. These are accessed relative to the folder that contains `fs2zef.sh`.

- Include updated `import_segmentation.zef` and an example `electrodes.dat` file under `mri2mesh/`.

Closes #192 . Do not merge until ready.

2023-05-07 08:41 UTC, mshavliuk requested changes

2023-05-07 08:41 UTC, mshavliuk commented on +mri2mesh/fs2zef.m
> +    FSL_DIR = fullfile("/", "usr", "local", "fsl");
The `FSL_DIR` path is hardcodded which has caused the error:
```
Checking environment…
Error using mri2mesh.fs2zef (line 135)
The FreeSurfer environment variable FSL_DIR was not set to point to an existing FreeSurfer folder 'fsl'. Set the variable in the shell that started Matlab and try again.
```



Moreover, I didn't manage to find an `fsl` dir on my system by running `find / -type d -name "fsl"`.

2023-05-07 08:41 UTC, mshavliuk commented on +mri2mesh/fs2zef.m
> +    SUBJECTS_DIR = fullfile(FREESURFER_HOME, "subjects") ;
It sets the `SUBJECTS_DIR` variable to `$FREESURFER_HOME/subjects` even though that variable is expected to already exist and have some value, which will be ignored.

Here's the output of `source $FREESURFER_HOME/SetUpFreeSurfer.sh`:
```
-------- freesurfer-darwin-macOS-7.3.2-20220804-6354275 --------
Setting up environment for FreeSurfer/FS-FAST (and FSL)
FREESURFER_HOME   /Applications/freesurfer/7.3.2
FSFAST_HOME       /Applications/freesurfer/7.3.2/fsfast
FSF_OUTPUT_FORMAT nii.gz
SUBJECTS_DIR      /Users/mikhail/freesurfer_subjects
MNI_DIR           /Applications/freesurfer/7.3.2/mni
```

2023-05-07 08:49 UTC, SeSodesa commented on +mri2mesh/fs2zef.m
> +    FSL_DIR = fullfile("/", "usr", "local", "fsl");
More thorough checks regarding environment variables should obviously be added, similar to how they are in `$FREESURFER_HOME/FREESURFER_ENV.sh`, which is sourced by `$FREESURFER_HOME/SetUpFreeSurfer.sh`. I'll implement them as soon as possible.

2023-05-07 08:50 UTC, mshavliuk commented on +mri2mesh/README.md
> +# mri2mesh
I like how detailed you've described the `fs2zef` function 👍

I wonder, if this readme file is the best place to store the documentation about it or we should better transfer all this content to https://github.com/sampsapursiainen/zeffiro_interface/wiki/Notes:-Importing-Segmentation-from-FreeSurfer wiki page?

I would assume that the user of ZI will rather start from exploring the wiki pages rather than roaming between the source code directories and reading existing files. In case if they don't know if the `mri2mesh` is the tool they need, they will not even open the directory and won't see this documentation. What do you think?

2023-05-07 08:54 UTC, mshavliuk requested changes

2023-05-07 08:54 UTC, mshavliuk commented on scripts/scripts_for_importing/mri2mesh/fs2zef.sh
>  #!/bin/bash
What about `scripts/scripts_for_importing/mri2mesh` directory? Do you think it's wise to keep both versions of the script?

I would suggest to stick to a single decision and delete everything that is outdated, so there's no confusion such as "which fs2zef do you mean, .sh or .m" or "which mri2mesh directory, with matlab or with shell"

2023-05-08 09:10 UTC, SeSodesa commented on scripts/scripts_for_importing/mri2mesh/fs2zef.sh
>  #!/bin/bash
I absolutely agree that the redundant folders should be done away with. I just want to make sure the Matlab version first works and then do the deletion in one swell commit, dedicated to precisely that and nothing else.

2023-05-08 09:12 UTC, SeSodesa commented on +mri2mesh/README.md
> +# mri2mesh
Yeah, there should be one main source of truth. It makes sense to place the information in the wiki.

2023-05-08 10:55 UTC, SeSodesa commented on +mri2mesh/fs2zef.m
> +    FSL_DIR = fullfile("/", "usr", "local", "fsl");
@mshavliuk I changed how the environment variables are loaded, and I'm now crossing my fingers that this bug is done away with. The function should now check for existing variables before setting the values to assumed defaults.

I didn't get much sleep last night and this was done while being completely cross-eyed, so please tell me if something is still amiss on your end.

2023-05-10 19:54 UTC, mshavliuk commented on +mri2mesh/fs2zef.m
> +    FSL_DIR = fullfile("/", "usr", "local", "fsl");
Now this seems to work properly! I didn't face any issues with FSL even though it's not installed on my system

2023-05-10 20:05 UTC, mshavliuk approved these changes
Awesome job, everything seems to work smoothly ✨

Let's also not forget to (in another PR?):
- [ ] Remove an outdated fs2zef.sh script
- [ ] Move the documentation to the wiki page and refer to it from the readme.md or from the script file itself

2023-05-11 05:01 UTC, SeSodesa commented
> Awesome job, everything seems to work smoothly ✨
> 
> Let's also not forget to (in another PR?):
> 
>     * [ ]  Remove an outdated fs2zef.sh script
> 
>     * [ ]  Move the documentation to the wiki page and refer to it from the readme.md or from the script file itself

The `README` from `+mri2mesh` should already be on the Wiki pages ([link]). We might consider that item resolved already, unless there is still something that could be improved on the page.

[link]: https://github.com/sampsapursiainen/zeffiro_interface/wiki/Importing-a-Segmentation-from-FreeSurfer

2023-05-11 05:11 UTC, SeSodesa commented
I think I will squash the commits and merge this, then, since the `README` has already been copied over to the wiki pages. We can do the removal of the old redundant files in a separate context, dedicated to it and only it. This will make it easier to find a point in the project history where the removal was done, in case something will be missed.

2023-05-11 05:27 UTC, merged