Allow importing electrodes to an existing project
sampsapursiainen/zeffiro_interface pull request #223
Opened 2023-05-17 06:43 UTC by SeSodesa

- Adds the package `import` with the function `electrodes_from`, which reads electrode positions and labels from a given text file.
- Adds an <kbd>Import electrodes</kbd> button to **Menu tool > Import**.

2023-05-18 07:50 UTC, SeSodesa commented
This now seems to somewhat work on my fork of the project ([link]), at least with the electrode file you provided, but the question still remains whether the fields that the electrode labels and numerical data are saved to are the desired ones. Currently they are set as `zef.s2_name_list` and `zef.sensors`. Also, I have not yet tested this with data that contains complete electrode model (CEM) fields. A bit more documentation still needs to be added, as well.

I'll upload the data to this repo as well, once I have a machine with the proper permissions set up available to me (my work computer). I couldn't be bothered to set up the required expiring tokens on our workstations for multiple remotes.

[link]: https://github.com/SeSodesa/zeffiro_interface/tree/222-allow-importing-electrodes-to-an-existing-project

2023-05-19 06:32 UTC, mshavliuk requested changes
The new import module looks great and documented nicely, great work 👏

For some reason the electrodes do not appear in the Segmentation tool at the moment, but as I understand it's still WIP.

Also, I've noticed one minor bug: when I'm closing the file picker for the electrodes import it complains about the wrong file type:

https://github.com/sampsapursiainen/zeffiro_interface/assets/6589665/ed223031-76ed-47e7-ad0a-d210e8c464fa

2023-05-19 06:32 UTC, mshavliuk commented on +import/electrodes_from_csv.m
> +    electrode_labels = repmat ( kwargs.MISSING_LABEL, n_of_rows, 1 ) ;
So eventually, if the names of the sensors were not specified, all of them will be named "N/A"? In such case I would prefer the previous way of defining names for them, by enumerating from index 1 and so on.

2023-05-19 07:37 UTC, SeSodesa commented on +import/electrodes_from_csv.m
> +    electrode_labels = repmat ( kwargs.MISSING_LABEL, n_of_rows, 1 ) ;
This should now be resolved. The electrodes with missing labels will be named `SN` ,where `N` is the row of the electrode in the input file, if no label is given.

2023-05-19 07:38 UTC, SeSodesa commented on +import/electrodes_from_csv.m
> +    electrode_labels = repmat ( kwargs.MISSING_LABEL, n_of_rows, 1 ) ;
Also, the case of a user pressing "Cancel" in the file selector should also be handled now.

2023-05-23 13:44 UTC, merged